---
- name: getting all azure VM facts
  hosts: localhost

  tasks:
    - name: running the facts module
      azure_rm_virtualmachineimage_info:
        location: westeurope
        publisher: RedHat
        offer: RHEL
        sku: "{{ release }}"
      # version: 8.0.2019050711
      register: vm_results

    - name: return data
      debug:
        var: vm_results
