---
- name: shut down all azure hosts
  hosts: all
  connection: local

  tasks:
    - name: calling startup
      azure_rm_virtualmachine:
        name: "{{ inventory_hostname }}"
        resource_group: automata
        started: true
