- name: create Azure VM
  hosts: localhost
  vars_files: 
#    - /home/ansible/secvar/azure_cred.yml
   - /home/ansible/secvar/ssh_keys.yml

  tasks: 
  - name: create resource groups
    azure_rm_resourcegroup:
      name: "{{ resourcegroup_name }}"
      location: westeurope
      tags:
        testing: testing

  - name: Create a virtual network
    azure_rm_virtualnetwork:
      name: firstnetwork
      resource_group: "{{ resourcegroup_name }}"
      address_prefixes_cidr:
          - "10.1.0.0/16"
          - "172.100.0.0/16"
      dns_servers:
          - "127.0.0.1"
          - "127.0.0.2"
      tags:
          testing: testing
          delete: on-exit

  - name: Create a subnet
    azure_rm_subnet:
      name: firstsubnet
      virtual_network_name: firstnetwork
      resource_group: "{{ resourcegroup_name }}"
      address_prefix_cidr: "10.1.0.0/24"
      state: present
  
  - name: setup first jumphost
    azure_rm_virtualmachine:
      resource_group: "{{ resourcegroup_name }}"
      name: jumphost
      vm_size: Standard_A2
      admin_username: ansible
      ssh_password_enabled: false
      ssh_public_keys: 
      - path: /home/ansible/.ssh/authorized_keys
        key_data: "{{ automata_sshkey }}"
      image:
        publisher: RedHat
        offer: RHEL
        sku: 8.1
        version: latest
    
