---
- name: Create a VIP, pool
  hosts: f5
  connection: local

  tasks:
   - name: Create a pool
     bigip_pool:
         lb_method: ratio-member
         name: web-pool
         provider: 
           password: admin
           server: f5
           user: admin
           validate_certs: no
         slow_ramp_time: 120
         state: present
         partition: Common
         monitors:
           - http
     delegate_to: localhost
