---
- name: Create a SelfIP
  hosts: f5
  connection: local

  tasks:
    - name: Create a SelfIP
      delegate_to: localhost
      f5networks.f5_modules.bigip_selfip:
        address: 10.0.122.10
        netmask: 255.255.255.0
        vlan: web-vlan1
        name: web-selfip1
        provider:
          password: admin
          server: f5
          user: admin
          validate_certs: false
        state: present
