---
- name: Create a VIP, pool
  hosts: f5
  connection: local

  tasks:
    - name: Create a VLAN
      delegate_to: localhost
      f5networks.f5_modules.bigip_vlan:
        untagged_interfaces: 1.1
        name: web-vlan1
        password: admin
        server: f5
        user: admin
        validate_certs: false
        state: absent
