---
- name: drop specific hosts from insights registration 
  vars:
    project_name: "changeme"
  hosts: rhel_vms 

  tasks: 
  - name: unregister hosts
    redhat.insights.insights_register: 
      state: absent
