---
- name: install packages
  hosts: all
  become: true
  vars:
    packages:
      - vim

  tasks:
    - name: package installs
      ansible.builtin.package:
        name: vim
        state: latest
