---
- name: rudimentary wrapper arpund virsh instead of a proper libvirt plugin
  become: true
  user: ansible
  hosts: gateway

  tasks:
    - name: run wrapper on gateway
      ansible.builtin.command: /home/ansible/inventory_wrapper.sh

    - name: fetch output
      ansible.builtin.fetch:
        src: /home/ansible/hosts
        dest: /tmp/hosts

#  - name: converting and importing 
#    shell: "ansible-inventory -i /tmp/hosts --list > /tmp/hosts.json"
#    delegate_to: localhost

- name: copying ini
  become: true
  user: ansible
  hosts: AAP22

  tasks:
    - name: push output
      ansible.builtin.copy:
        src: /tmp/hosts
        dest: /var/lib/awx/hosts
        owner: awx
