---
- name: importing data
  become: no
  user: awx
  hosts: AAP22

  - name: run import 
    shell: 'awx-manage inventory_import --source /tmp/hosts.json --inventory-name "Hetzner Inventory"' 
     


