---
- name: importing data
  become: false
  user: awx
  hosts: AAP22

  tasks:
    - name: run import
      ansible.builtin.shell: awx-manage inventory_import --source /var/lib/awx/hosts --inventory-name "I2"
