---
- name: importing data
  become: no
  user: awx
  hosts: AAP22

  tasks: 
  - name: run import 
    shell: 'awx-manage inventory_import --source /var/lib/awx/hosts --inventory-name "Hetzner_Inventory"'
     


