---
- name: deploy an NFS share on NetApp
  hosts: localhost
  vars_files:
    - netapp_allvars.yml

  tasks:
  - name: Create Aggregates and wait 5 minutes until aggregate is online
    na_ontap_aggregate:
      state: present
      service_state: online
      name: aggr01
      disk_count: 5
      wait_for_online: True
      time_out: 60
      use_rest: "{{ netapp_config_use_rest }}"
      https: "{{ netapp_config_https }}"
      validate_certs: "{{ netapp_config_validate_certs }}"
      hostname: "{{ netapp_node2_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"


  - name: Create SVM
    na_ontap_svm:
      state: present
      name: svm02
      root_volume: svm02_vol01
      root_volume_aggregate: aggr01
      root_volume_security_style: unix
      use_rest: "{{ netapp_config_use_rest }}"
      https: "{{ netapp_config_https }}"
      validate_certs: "{{ netapp_config_validate_certs }}"
      hostname: "{{ netapp_node2_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  - name: Create interface
    na_ontap_interface:
      state: present
      interface_name: svm02_if01
      home_port: e0b
      # home_node: rhnetappcluster-2-01
      home_node: "{{ netapp_node2_hostname }}-01"
      role: data
      protocols: 
        - nfs
        - cifs
      admin_status: up
      failover_policy: local-only
      firewall_policy: data
      is_auto_revert: true
      # address: 192.168.122.66
      # netmask: 255.255.255.0
      address: "{{ netapp_node2_svm_interface }}"
      netmask: "{{ netapp_node2_svm_interface_mask }}"
      force_subnet_association: false
      dns_domain_name: test.com
      listen_for_dns_query: no
      is_dns_update_enabled: no
      vserver: svm02
      use_rest: "{{ netapp_config_use_rest }}"
      https: "{{ netapp_config_https }}"
      validate_certs: "{{ netapp_config_validate_certs }}"
      hostname: "{{ netapp_node2_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  - name: change nfs status
    na_ontap_nfs:
      state: present
      service_state: started
      vserver: svm02
      nfsv3: disabled
      nfsv4: enabled
      nfsv41: enabled
      tcp: enabled
      udp: enabled
#      vstorage_state: disabled
      nfsv4_id_domain: example.com
      use_rest: "{{ netapp_config_use_rest }}"
      https: "{{ netapp_config_https }}"
      validate_certs: "{{ netapp_config_validate_certs }}"
      hostname: "{{ netapp_node2_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  - name: Modify default Export Policy Rule
    na_ontap_export_policy_rule: 
      state: present 
      policy_name: default
      vserver: "svm02"
      client_match: 0.0.0.0/0  
      ro_rule: any 
      rw_rule: any
      super_user_security: none 
      use_rest: "{{ netapp_config_use_rest }}"
      https: "{{ netapp_config_https }}"
      validate_certs: "{{ netapp_config_validate_certs }}"
      hostname: "{{ netapp_node2_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  - name: Create Export Policy
    na_ontap_export_policy:
      state: present
      name: policy01
      vserver: svm02
      use_rest: "{{ netapp_config_use_rest }}"
      https: "{{ netapp_config_https }}"
      validate_certs: "{{ netapp_config_validate_certs }}"
      hostname: "{{ netapp_node2_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  - name: Create ExportPolicyRule
    na_ontap_export_policy_rule:
      state: present
      name: policy01
      vserver: svm02
      # client_match: 192.168.122.0/24
      client_match: 0.0.0.0/0  
      ro_rule: any
      rw_rule: any
      protocol: nfs4
      super_user_security: any
      allow_suid: true
      use_rest: "{{ netapp_config_use_rest }}"
      https: "{{ netapp_config_https }}"
      validate_certs: "{{ netapp_config_validate_certs }}"
      hostname: "{{ netapp_node2_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  - name: Create FlexVol
    na_ontap_volume:
      state: present
      name: svm02_datavol01
      is_infinite: False
      junction_path: "/svm02_datavol01"
      aggregate_name: aggr01
      size: 500
      size_unit: mb
      space_guarantee: none
      tiering_policy: auto
      policy: policy01
      percent_snapshot_space: 20
#      qos_policy_group: max_performance_gold
      vserver: svm02
      wait_for_completion: True
#      space_slo: none
      nvfail_enabled: False
      comment: "Charlie was here!"
      use_rest: "{{ netapp_config_use_rest }}"
      https: "{{ netapp_config_https }}"
      validate_certs: "{{ netapp_config_validate_certs }}"
      hostname: "{{ netapp_node2_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
