---
- name: webserver setup
  user: ansible 
  hosts: all

  tasks:
    - name: install webserver pkg
      yum:
        name: httpd
        state: present

    - name: ensure firewalld and its python module is installed
      yum:
        name:
          - firewalld 
          - python-firewall
        state: present
      when: ansible_distribution_major_version == "7"

    - name: ensure firewalld and its python module is installed
      yum:
        name:
          - firewalld 
          - python3-firewall
        state: present
      when: ansible_distribution_major_version == "8"

    - name: enable webserver
      systemd:
        name: httpd
        enabled: yes

    - name: start webserver
      systemd:
        name: httpd
        state: started

    - name: Open port 80
      firewalld: 
        service: http 
        permanent: true 
        state: enabled

    - name: start the firewalld service
      systemd:
        name: firewalld
        state: restarted
