---
- name: manage libvirt guests 
  user: ansible 
  hosts: baremetal
  vars:
      project_name: web
      number_of_hosts: 3
      os_type: rhel
      os_version: 7.6

  tasks:
    - name: create VM {{ os_type }}-{{ project_name }} items by cloning image
      command: "virt-clone --original=rhel{{ os_version }}-img --name={{ os_type }}-{{ project_name }}{{ item }} --auto-clone"
      with_sequence: count={{ number_of_hosts }}

    - name: sysprep VM {{ os_type }}-{{ project_name }} items
      command: "virt-sysprep -d {{ os_type }}-{{ project_name }}{{ item }} --hostname {{ os_type }}-{{ project_name }}{{ item }} --operations defaults" 
      with_sequence: count={{ number_of_hosts }}

    - name: transfer/prep SSH public key or keys to be injected into the images. 
      copy: 
        src: /opt/data/keys/ssh_pubkey
        dest: /home/ansible/addkey

    - name: sysprep VM plant keys {{ os_type }}-{{ project_name }} items
      command: "virt-sysprep -d {{ os_type }}-{{ project_name }}{{ item }} --ssh-inject ansible:file:/home/ansible/addkey --selinux-relabel" 
      with_sequence: count={{ number_of_hosts }}
    
    - name: set description to {{ os_type }}-{{ project_name }} items
      command: "virsh desc {{ os_type }}-{{ project_name }}{{ item }} --title {{ os_type }}-{{ project_name }}{{ item }}"
      with_sequence: count={{ number_of_hosts }}
    
    - name: start guest VMs "{{ os_type }}-{{ project_name }} items"
      virt:
          name: "{{ os_type }}-{{ project_name }}{{ item }}"
          state: running
      with_sequence: count={{ number_of_hosts }}

    - name: allow DHCP/DNS to register
      pause:
        minutes: 1
    

