---
- name: Setup Zabbix client
  user: ansible 
  hosts: rhel_vms
  vars:
    firewall_allowed_udp_ports: 
      - 10050
      - 10051
    firewall_allowed_tcp_ports:
      - 10050
      - 10051

  tasks:
    - name: Install Zabbix agent
      yum: 
        name: zabbix40-agent
        state: latest 

    - name: make sure zabbix client service is enabled
      systemd:
        name: zabbix-agent
        enabled: yes

    - name: copy zabbix config
      copy: 
        src: configs/zabbix_agentd.conf
        dest: /etc/

    - name: Create a new host or update an existing host's info
      local_action:
        module: zabbix_host
        server_url: http://zabbix/zabbix
        login_user: Admin
        login_password: zabbix
        host_name: "{{ inventory_hostname }}"
        visible_name: "{{ inventory_hostname }}"
        description: This is the {{ inventory_hostname }} description
        inventory_mode: manual
        host_groups:
          - RHEL Servers
        link_templates:
          - Template App HTTP Service
          - Template App SSH Service
          - Template Module ICMP Ping
          - Template OS Linux
        status: enabled
        state: present
        interfaces: 
          - type: agent
            main: 1
            dns: "{{ inventory_hostname }}"
            ip: "{{ ansible_eth0.ipv4.address }}"

    - name: make sure zabbix client is running
      systemd:
        name: zabbix-agent
        state: started

    - name: ensure firewalld installation
      package: 
        name: firewalld
        state: latest

    - name: enable firewalld service
      service: 
        name: firewalld
        state: started

    - name: Open ports
      firewalld: 
        port: "{{ item }}"
        permanent: true 
        state: enabled
      with_items:
        - 10050/tcp
        - 10051/tcp
    
    - name: Open port 10050
      firewalld: 
        port: "{{ item }}"
        immediate: true 
        state: enabled
      with_items:
        - 10050/tcp
        - 10051/tcp

    - name: restart the firewalld service
      systemd:
        name: firewalld
        state: restarted

