---
- name: collection based insights installation
  hosts: all
  collections:
    - redhat.insights

  tasks:
    - when: ansible_os_family == 'RedHat'
      ansible.builtin.include_role:
        name: redhat.insights.insights_client

    - name: install compliance required packages (openscap)
      ansible.builtin.package:
        state: latest
        name:
          - scap-security-guide
          - openscap-scanner
          - openscap
