---
- name: update all packages
  hosts: all

  tasks: 
  - name: after contentview change s-m refresh is necessary
    command: subscription-manager refresh

  - name: update all
    yum: 
      state: latest
      name: '*'

  - name: reboot
    reboot:

  - name: set content host facts straight
    command: subscription-manager facts --update


