---
- name: satellite preparation
  user: ansible 
  hosts: all
  vars:
    sat_version: 6.8

  tasks:
    - name: sync /etc/hosts
      copy:
        src: /etc/hosts
        dest: /etc

    - name: make sure ntpd client service is enabled
      systemd:
        name: chronyd
        enabled: yes

    - name: make sure ntpd client is running
      systemd:
        name: chronyd
        state: started

    - name: make sure rhsmcertd is running
      systemd:
        name: rhsmcertd
        state: started

    - name: download katello rpm for retistration from satellite
      get_url:
        url: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        dest: /var/tmp

    - name: install RPM with yum
      yum: 
        name: /var/tmp/katello-ca-consumer-latest.noarch.rpm
        state: present

    - name: Register to satellite with activationkey and consume subscriptions 
      redhat_subscription:
        state: present
        activationkey: NewKey_1
        org_id: SuperCorp
        auto_attach: true

    - name: Set RHSM release version
      rhsm_release:
        release: "8.1"

    - name: enable Satellite Host Tools repo 
      rhsm_repository:
        name: "rhel-7-server-satellite-tools-{{ sat_version }}-rpms"
        # name: "rhel-8-server-satellite-tools-{{ sat_version }}-rpms"
        #  name: "satellite-tools-6.8-for-rhel-8-x86_64-rpms"
        state: enabled

    - name: install katello-agent and katello-host-tools
      yum: 
        name: katello-agent
        state: present
