---
- name: webserver setup
  user: ansible
  hosts: all

  tasks:
    - name: install webserver pkg
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: enable webserver
      ansible.builtin.systemd:
        name: httpd
        enabled: true

    - name: start webserver
      ansible.builtin.systemd:
        name: httpd
        state: started
