---
- name: manage ssh keys
  hosts: localhost
  connection: local
  vars:
    host_name: hetzner

  tasks:
    - name: remove ssh known_hosts entries locally
      ansible.builtin.known_hosts:
        name: "{{ host_name }}"
        state: absent

    - name: scan for keys
      # shell: ssh-keyscan -t ecdsa  {{ item }},$(dig +short {{ item }})
      register: ssh_key_scanned
      ansible.builtin.shell: ssh-keyscan -t ecdsa  {{ host_name }}

    - ansible.builtin.debug:
        var: ssh_key_scanned

    - name: add ssh known_hosts entries locally
      ansible.builtin.known_hosts:
        name: "{{ host_name }}"
        state: present
        path: /home/ansible/.ssh/known_hosts
        key: "{{ ssh_key_scanned.stdout }}"

    - name: fix known_host ownership
      ansible.builtin.file:
        path: /home/ansible/.ssh/known_hosts
        owner: ansible
        group: ansible
