---
- name: 
  hosts: all

  roles:
  - role: redhatinsights.insights-client
    # insights_display_name: "{{ inventory_hostname }}"
    when: ansible_os_family == 'RedHat'

  tasks: 
  - name: install compliance required packages (openscap)
    package: 
      state: latest
      name: 
        - scap-security-guide
        - openscap-scanner
        - openscap

