---
- name: delegated SSH key parsing
  hosts: gatewayed
  connection: local
  gather_facts: false
  tasks:
    - register: new_host_fingerprint
      delegate_to: hetzner
      ansible.builtin.command: ssh-keyscan -t ecdsa {{ host_name }}

    - with_items: "{{ new_host_fingerprint.stdout_lines }}"
      ansible.builtin.lineinfile:
        dest: /home/ansible/.ssh/known_hosts
        line: "{{ item }}"
