---
- name: manage libvirt guests
  hosts: localhost
  connection: local
  vars:
    host_name: web

  tasks:
    - name: remove ssh known_hosts entries locally
      ansible.builtin.known_hosts:
        name: "{{ host_name }}"
        path: /home/ansible/.ssh/known_hosts
        state: absent

    #    - debug: var="{{ os_type }}-{{ project_name }}{{ item }}"
    #      with_sequence: count="{{ number_of_hosts }}"
