---
- name:
  hosts: all

  roles:
    - role: redhatinsights.insights-client
    # insights_display_name: "{{ inventory_hostname }}"
      when: ansible_os_family == 'RedHat'

  tasks:
    - name: install compliance required packages (openscap)
      ansible.builtin.package:
        state: latest
        name:
          - scap-security-guide
          - openscap-scanner
          - openscap

    - name: run insights compliance
      ansible.builtin.import_role:
        name: redhat.insights.compliance
        tasks_from: run

  #   - name: run compliance content upload 
  #    shell: "insights-client --compliance" 
