---
- name: Setup Zabbix client
  user: ansible
  hosts: rhel_vms
  vars:
    firewall_allowed_udp_ports:
      - 10050
      - 10051
    firewall_allowed_tcp_ports:
      - 10050
      - 10051

  tasks:
    - name: Install Zabbix agent
      ansible.builtin.yum:
        name: zabbix40-agent
        state: latest

    - name: make sure zabbix client service is enabled
      ansible.builtin.systemd:
        name: zabbix-agent
        enabled: true

    - name: copy zabbix config
      ansible.builtin.copy:
        src: configs/zabbix_agentd.conf
        dest: /etc/

    - name: Create a new host or update an existing host's info
      local_action:
        module: community.zabbix.zabbix_host
        server_url: http://zabbix/zabbix
        login_user: Admin
        login_password: zabbix
        host_name: "{{ inventory_hostname }}"
        visible_name: "{{ inventory_hostname }}"
        description: This is the {{ inventory_hostname }} description
        inventory_mode: manual
        host_groups:
          - RHEL Servers
        link_templates:
          - Template App HTTP Service
          - Template App SSH Service
          - Template Module ICMP Ping
          - Template OS Linux
        status: enabled
        state: present
        interfaces:
          - type: agent
            main: 1
            dns: "{{ inventory_hostname }}"
            ip: "{{ ansible_eth0.ipv4.address }}"

    - name: make sure zabbix client is running
      ansible.builtin.systemd:
        name: zabbix-agent
        state: started

    - name: ensure firewalld installation
      ansible.builtin.package:
        name: firewalld
        state: latest

    - name: enable firewalld service
      ansible.builtin.service:
        name: firewalld
        state: started

    - name: Open ports
      with_items:
        - 10050/tcp
        - 10051/tcp
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled

    - name: Open port 10050
      with_items:
        - 10050/tcp
        - 10051/tcp
      ansible.posix.firewalld:
        port: "{{ item }}"
        immediate: true
        state: enabled

    - name: restart the firewalld service
      ansible.builtin.systemd:
        name: firewalld
        state: restarted
