---
- name: satellite preparation
  user: ansible
  hosts: TJtest

  tasks:
    - name: sync /etc/hosts
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /etc

    - name: make sure ntpd client service is enabled
      ansible.builtin.systemd:
        name: chronyd
        enabled: true

    - name: make sure ntpd client is running
      ansible.builtin.systemd:
        name: chronyd
        state: started

    - name: make sure rhsmcertd is running
      ansible.builtin.systemd:
        name: rhsmcertd
        state: started

    - name: download katello rpm for retistration from satellite
      ansible.builtin.get_url:
        url: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        dest: /var/tmp

    - name: install RPM with yum
      ansible.builtin.yum:
        name: /var/tmp/katello-ca-consumer-latest.noarch.rpm
        state: present

    - name: Register to satellite with activationkey and consume subscriptions
      community.general.redhat_subscription:
        state: present
        activationkey: NewKey_1
        org_id: SuperCorp
        auto_attach: true

    - name: enable Satellite Host Tools repo
      community.general.rhsm_repository:
        name: rhel-7-server-satellite-tools-6.4-rpms
        state: enabled

    - name: install katello-agent and katello-host-tools
      ansible.builtin.yum:
        name: katello-agent
        state: present
