---
- name: satellite preparation
  user: ansible
  hosts: rhel_vms

  tasks:
    - name: make sure rhsmcertd is running
      ansible.builtin.systemd:
        name: rhsmcertd
        state: started

    - name: install RPM with yum
      ansible.builtin.yum:
        name: katello-ca-consumer
        state: absent

    - name: Unreg from Sat
      community.general.redhat_subscription:
        state: absent
        activationkey: NewKey_1
        org_id: SuperCorp

    - name: remove katello-agent and katello-host-tools
      ansible.builtin.yum:
        name:
          - katello-agent
          - katello-host-tools
        state: absent

    # foreman module is deprecated, need to use the theforeman collection, but until then command
    #    - name: drop hosts entry from sat
    #      foreman:
    #        username: admin
    #        password: admin
    #        server_url: https://satellite.example.com
    #        entity: host
    #        params:
    #          name: "{{ inventory_hostname }}"
    #          state: absent

    - name: unsubscribe hosts
      ansible.builtin.shell: /usr/bin/subscription-manager unregister ; /usr/bin/subscription-manager clean
