---
- name: manage libvirt guests 
  hosts: gatewayed
  connection: local
  vars:
      host_name: web

  tasks:
    - name: remove ssh known_hosts entries locally
      known_hosts:
        name: "{{ item }}"
        path: /home/ansible/.ssh/known_hosts
        state: absent 
      with_items: "{{ groups['rhel_vms'] }}"

#    - debug: var="{{ os_type }}-{{ project_name }}{{ item }}"
#      with_sequence: count="{{ number_of_hosts }}"

