---
- name: set up hetzner subscription
  hosts: all
  vars_files:
    - /home/ansible/secvar/cred.yml

  tasks:
    - name: setup subscription
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_access_account }}"
        password: "{{ rhsm_access_token }}"
        auto_attach: true
