---
- name: webserver setup
  user: ansible
  hosts: all

  tasks:
    - name: install webserver pkg
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: ensure firewalld and its python module is installed
      when: ansible_distribution_major_version == "7"
      ansible.builtin.yum:
        name:
          - firewalld
          - python-firewall
        state: present

    - name: ensure firewalld and its python module is installed
      when: ansible_distribution_major_version == "8"
      ansible.builtin.yum:
        name:
          - firewalld
          - python3-firewall
        state: present

    - name: enable webserver
      ansible.builtin.systemd:
        name: httpd
        enabled: true

    - name: start webserver
      ansible.builtin.systemd:
        name: httpd
        state: started

    - name: Open port 80
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled

    - name: start the firewalld service
      ansible.builtin.systemd:
        name: firewalld
        state: restarted
