---
- name: set up SSL Proxy for supercorp
  hosts: hetzner,gatewayed

  tasks:
    - name: copy configfile for proxyconfig content
      when: ansible_hostname == "prhel"
      ansible.builtin.copy:
        src: /home/ansible/projects/ansible-hetzner/stuff/supercorpat.conf
        dest: /etc/httpd/conf.d/

    - name: set the right IP for ansible-h
      with_items:
        - ProxyPass / http://{{ hostvars['ansible-h']['ansible_eth0']['ipv4']['address'] }}/
        - ProxyPassReverse / http://{{ hostvars['ansible-h']['ansible_eth0']['ipv4']['address'] }}/
      when: ansible_hostname == "prhel"
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf.d/supercorpat.conf
        insertafter: ^# Insert TOWER Proxymapping here
        line: "{{ item }}"

    - name: set the right IP for satellite-h
      with_items:
        - ProxyPass / http://{{ hostvars['satellite-h']['ansible_eth0']['ipv4']['address'] }}/
        - ProxyPassReverse / http://{{ hostvars['satellite-h']['ansible_eth0']['ipv4']['address'] }}/
      when: ansible_hostname == "prhel"
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf.d/supercorpat.conf
        insertafter: ^# Insert SATELLITE Proxymapping here
        line: "{{ item }}"

    - name: restart httpd
      when: ansible_hostname == "prhel"
      ansible.builtin.systemd:
        name: httpd
        state: restarted

    - name: Open port 80
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Open port 443
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled

    - name: start the firewalld service
      ansible.builtin.systemd:
        name: firewalld
        state: restarted
