---
- name: test vm list
  hosts: all
  connection: local
  vars:
    - vcenter_hostname: vcenter.home.lab
    - vcenter_username: administrator@vSphere.local
    - vcenter_password: TotalSecret!1

  tasks:
    - name: Gather all registered virtual machines
      delegate_to: localhost
      register: vmfacts
      alancoding.vmware.vmware_vm_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false

    - name: show me
      ansible.builtin.debug:
        var: vmfacts.virtual_machines
