---
- name: set local hostname
  hosts: win_vms

  tasks:
    - name: Change the hostname to new_hostname
      register: res
      ansible.windows.win_hostname:
        name: "{{ inventory_hostname }}"

    - name: reboot to get new hostname take effect
      ansible.windows.win_reboot:
    #      when: res.reboot_required
