---
- name: set up/remove local windows server users
  hosts: win_vms

  tasks:
    - name: Add user
      ansible.windows.win_user:
        name: bob
        password: B0bpass1
        state: present
        groups:
          - Administrators
