---
- name: Install firewalld
  ansible.builtin.package:
    name: firewalld

- name: Install python-firewall
  when: ansible_python_version|version_compare('3', '<')
  ansible.builtin.package:
    name: python-firewall

- name: Install python3-firewall
  when: ansible_python_version|version_compare('3', '>=')
  ansible.builtin.package:
    name: python3-firewall

- name: Enable and start firewalld service
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
